### ISSUE TITLE
VSCode Integration

### ISSUE THREAD

**Issue by tonyfromundefined** [reason-seoul/yarn-plugin-rescript#12]
Hmm... Intellisense is not working properly in Visual Studio Code with [rescript extension](https://github.com/rescript-lang/rescript-vscode).

How to integrate with VSCode with `yarn-plugin-rescript`?

**Comment by cometkim** [comment]
There is nothing special about it. Make sure your yarn project is configured well.

- Is `bsconfig.json` located correctly?
- Is the `node_modules` directory created properly after installation? If not, you can fix it by running `yarn res link` manually.
